### PR TITLE
Incorrect logic in CIS 1.09 Closes #79

### LINKED ISSUE #79: Incorrect logic in CIS 1.09
**Describe the bug**
Separation of duties is being incorrectly calculated by the SQL in CIS 1.09

The SQL statement selects 2 groups of users and then creates an alarm if the same user appears in both groups.  However, the current query guarantees that anyone in group A (`kms_admin_users`) is also in group B (`kms_encrypt_decrypt_users`):

See:  https://github.com/turbot/steampipe-mod-gcp-compliance/blob/6acccf94ba98e9b3b78bc5b64b28723fd12e8882/query/kms/kms_key_separation_of_duties_enforced.sql#L27

### PR DESCRIPTION
**Pull request by khushboo9024**
### Checklist
- [ ] Issue(s) linked

### CODE REVIEW

File: query/kms/kms_key_separation_of_duties_enforced.sql [hunk 1]
```diff
@@ -24,18 +24,22 @@ kms_encrypt_decrypt_users as(
     project
   from
     users_with_roles
-  where assigned_role in ('roles/cloudkms.admin', 'roles/cloudkms.cryptoKeyEncrypterDecrypter', 'roles/cloudkms.cryptoKeyEncrypter', 'roles/cloudkms.cryptoKeyDecrypter')
+  where assigned_role in ( 'roles/cloudkms.cryptoKeyEncrypterDecrypter', 'roles/cloudkms.cryptoKeyEncrypter', 'roles/cloudkms.cryptoKeyDecrypter')
```
Comment (cbruno10) [inline query/kms/kms_key_separation_of_duties_enforced.sql:27]:
```suggestion
  where assigned_role in ('roles/cloudkms.cryptoKeyEncrypterDecrypter', 'roles/cloudkms.cryptoKeyEncrypter', 'roles/cloudkms.cryptoKeyDecrypter')
```

File: query/kms/kms_key_separation_of_duties_enforced.sql [hunk 2]
```diff
@@ -24,18 +24,22 @@ kms_encrypt_decrypt_users as(
...
 )
 select
   -- Required Columns
   distinct user_name as resource,
   case
     when user_name in (select user_name from kms_encrypt_decrypt_users) and user_name in (select user_name from kms_admin_users) then 'alarm'
```
Comment (cbruno10) [inline query/kms/kms_key_separation_of_duties_enforced.sql:33]:
```suggestion
    when user_name in (select user_name from kms_encrypt_decrypt_users) or user_name in (select user_name from kms_admin_users) then 'alarm'
```

Instead of adding 2 new conditions, could we just fix this issue by changing this line?

File: query/kms/kms_key_separation_of_duties_enforced.sql [hunk 3]
```diff
@@ -24,18 +24,22 @@ kms_encrypt_decrypt_users as(
...
+    when user_name in (select user_name from kms_encrypt_decrypt_users) then 'alarm'
+    when user_name in (select user_name from kms_admin_users) then 'alarm'
     else 'ok'
   end status,
   case
     when user_name in (select user_name from kms_encrypt_decrypt_users) and user_name in (select user_name from kms_admin_users)
```
Comment (cbruno10) [inline query/kms/kms_key_separation_of_duties_enforced.sql:39]: Instead of adding the 2 new reasons below could we construct a reason based on what roles they have assigned?

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@khushboo9024 Please see review, thanks!

**Review by cbruno10 — APPROVED** [review]
